"""update schema

Revision ID: 0ca3fcfbe15f
Revises: 271abba2705e
Create Date: 2025-11-20 20:12:10.726505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ca3fcfbe15f'
down_revision = '271abba2705e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in correct order (respecting foreign key dependencies)
    # First drop tables that depend on others
    op.drop_table('workout_logs')  # depends on exercises
    op.drop_table('user_workout_status')  # depends on workout_split_days
    op.drop_table('exercise_templates')  # depends on split_days
    
    # Then drop the tables they depended on
    op.drop_table('exercises')
    op.drop_table('workout_split_days')
    
    # Create new workout_sets table
    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=120), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Update split_days table
    with op.batch_alter_table('split_days', schema=None) as batch_op:
        batch_op.alter_column('muscle_groups',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.String(length=255),
               existing_nullable=True,
               postgresql_using='muscle_groups::text')
    
    # Update workout_sessions table
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('split_day_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.alter_column('assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'split_days', ['split_day_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('completed')
        batch_op.drop_column('split_day_id')
        batch_op.drop_column('user_id')

    op.create_table('workout_split_days',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workout_split_days_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('split_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('muscle_group', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['split_id'], ['splits.id'], name='workout_split_days_split_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workout_split_days_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('workout_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('workout_logs_exercise_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], name=op.f('workout_logs_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('workout_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_logs_pkey'))
    )
    op.create_table('exercise_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('split_day_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('default_sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('default_reps', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['split_day_id'], ['split_days.id'], name=op.f('exercise_templates_split_day_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exercise_templates_pkey'))
    )
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('muscle_group', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('exercises_pkey'))
    )
    op.create_table('user_workout_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('split_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_day_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_day_id'], ['workout_split_days.id'], name=op.f('user_workout_status_current_day_id_fkey')),
    sa.ForeignKeyConstraint(['split_id'], ['splits.id'], name=op.f('user_workout_status_split_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_workout_status_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_workout_status_pkey'))
    )
    op.drop_table('workout_sets')
    # ### end Alembic commands ###
