"""add is_template to splits

Revision ID: c200f35429e2
Revises: add_user_profile_fields
Create Date: 2025-11-24 09:56:48.556243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c200f35429e2'
down_revision = 'add_user_profile_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_template', sa.Boolean(), nullable=True))
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_template')

    # ### end Alembic commands ###
